# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RcRkzScLjpQ6T9fS0PSABugnUchNbb2_
"""

pip install google-api-python-client

import json
from googleapiclient.discovery import build
from urllib.parse import urlparse, parse_qs

def get_youtube_video_id(video_url):
    # Parse the video URL
    parsed_url = urlparse(video_url)

    # Extract the video ID from different parts of the URL
    video_id = parse_qs(parsed_url.query).get('v')

    if video_id:
        return video_id[0]

    # Try to extract the video ID from the path if not found in the query parameters
    path_components = parsed_url.path.split("/")
    for component in path_components:
        if component and '=' not in component:
            return component

    raise ValueError("Unable to extract video ID from the URL")

def fetch_youtube_comments(api_key, video_url):
    try:
        # Extract video ID
        video_id = get_youtube_video_id(video_url)

        # Initialize the YouTube Data API
        youtube = build('youtube', 'v3', developerKey=api_key)

        # Request comments for the video
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            textFormat="plainText",
        )

        response = request.execute()

        # Extract comments
        comments = [item['snippet']['topLevelComment']['snippet']['textDisplay'] for item in response['items']]

        return comments

    except Exception as e:
        print(f"Error: {e}")
        return []

# Replace 'YOUR_API_KEY' with the actual API key from the Google Cloud Console
api_key = 'AIzaSyAnKVOKRlnR0g0rldvQJWHGs6hoHDTqUH4'

# Replace 'YOUR_YOUTUBE_VIDEO_URL' with the actual URL of the YouTube video
video_url = 'https://youtu.be/QpzMWQvxXWk?si=KFT4ppAmkzHbmluW'

# Fetch comments
comments = fetch_youtube_comments(api_key, video_url)

# Print comments
for i, comment in enumerate(comments, start=1):
    print(f"Comment {i}: {comment}")
    print("---")